title: Dong A Restaurant - Finest Asian Cuisine
email: github.com/dong-a6
description: > # this means to ignore newlines until "baseurl:"
  "Die hohe Kunst erstklassiger asiatischer Kochkunst - im Gourmetrestaurant Dong A im KPM Hotel & Residences
  ist sie erlebbar"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "//dong-a6.github.io" # the base hostname & protocol for your site
github_username:  dong-a6

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json, _markdown]
